# Generated by Django 5.2.7 on 2025-10-14 13:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razao_social', models.CharField(max_length=200, verbose_name='Razão Social')),
                ('nome_fantasia', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nome Fantasia')),
                ('cnpj', models.CharField(max_length=18, unique=True, verbose_name='CNPJ')),
                ('telefone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
            ],
            options={
                'verbose_name': 'Fornecedor',
                'verbose_name_plural': 'Fornecedores',
            },
        ),
        migrations.CreateModel(
            name='Orgao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome do Órgão')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/', verbose_name='Logotipo')),
                ('cnpj', models.CharField(max_length=18, unique=True, verbose_name='CNPJ')),
                ('endereco', models.CharField(max_length=255, verbose_name='Endereço')),
                ('telefone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail de Contato')),
            ],
            options={
                'verbose_name': 'Órgão',
                'verbose_name_plural': 'Órgãos Públicos',
            },
        ),
        migrations.CreateModel(
            name='Processo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_processo', models.CharField(max_length=50, unique=True, verbose_name='Número do Processo')),
                ('objeto', models.TextField(verbose_name='Objeto da Licitação')),
                ('status', models.CharField(choices=[('FASE_INTERNA', 'Fase Interna'), ('PUBLICADO', 'Publicado'), ('AGUARDANDO_PROPOSTAS', 'Aguardando Propostas'), ('EM_ANALISE', 'Em Análise'), ('HOMOLOGADO', 'Homologado'), ('CANCELADO', 'Cancelado')], default='FASE_INTERNA', max_length=30, verbose_name='Status')),
                ('modalidade', models.CharField(choices=[('PREGAO', 'Pregão'), ('CONCORRENCIA', 'Concorrência'), ('CONCURSO', 'Concurso'), ('LEILAO', 'Leilão'), ('DIALOGO_COMPETITIVO', 'Diálogo Competitivo'), ('DISPENSA', 'Dispensa de Licitação'), ('INEXIGIBILIDADE', 'Inexigibilidade de Licitação')], max_length=30, verbose_name='Modalidade')),
                ('data_abertura', models.DateField(auto_now_add=True, verbose_name='Data de Abertura')),
                ('data_finalizacao', models.DateField(blank=True, null=True, verbose_name='Data de Finalização')),
                ('valor_estimado', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Valor Estimado')),
                ('orgao_responsavel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.orgao', verbose_name='Órgão Responsável')),
            ],
            options={
                'verbose_name': 'Processo',
                'verbose_name_plural': 'Processos',
            },
        ),
    ]
