# Generated by Django 5.2.7 on 2025-10-14 19:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Secretaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome da Secretaria')),
                ('orgao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secretarias', to='core.orgao', verbose_name='Órgão')),
            ],
            options={
                'verbose_name': 'Secretaria',
                'verbose_name_plural': 'Secretarias',
                'unique_together': {('orgao', 'nome')},
            },
        ),
        migrations.AddField(
            model_name='processo',
            name='secretaria_responsavel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.secretaria', verbose_name='Secretaria Responsável'),
        ),
    ]
