# Generated by Django 5.2.7 on 2025-10-15 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_secretaria_processo_secretaria_responsavel'),
    ]

    operations = [
        migrations.AddField(
            model_name='processo',
            name='justificativa',
            field=models.TextField(blank=True, help_text='Descreva em detalhes o porquê da contratação.', verbose_name='Justificativa da Necessidade'),
        ),
        migrations.AddField(
            model_name='processo',
            name='responsavel_demanda_cargo',
            field=models.CharField(blank=True, max_length=100, verbose_name='Cargo do Responsável'),
        ),
        migrations.AddField(
            model_name='processo',
            name='responsavel_demanda_matricula',
            field=models.CharField(blank=True, max_length=50, verbose_name='Matrícula do Responsável'),
        ),
        migrations.AddField(
            model_name='processo',
            name='responsavel_demanda_nome',
            field=models.CharField(blank=True, max_length=200, verbose_name='Nome do Responsável pela Demanda'),
        ),
        migrations.AlterField(
            model_name='processo',
            name='modalidade',
            field=models.CharField(choices=[('PREGAO', 'Pregão'), ('CONCORRENCIA', 'Concorrência'), ('CONCURSO', 'Concurso'), ('LEILAO', 'Leilão'), ('DIALOGO_COMPETITIVO', 'Diálogo Competitivo'), ('DISPENSA', 'Dispensa de Licitação'), ('INEXIGIBILI-DADE', 'Inexigibilidade de Licitação')], max_length=30, verbose_name='Modalidade'),
        ),
    ]
