# Generated by Django 5.2.7 on 2025-10-15 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_processo_justificativa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='processo',
            name='descricao_detalhada_objeto',
            field=models.TextField(blank=True, verbose_name='Descrição Detalhada do Objeto/Imóvel'),
        ),
        migrations.AddField(
            model_name='processo',
            name='vigencia_meses',
            field=models.IntegerField(blank=True, null=True, verbose_name='Prazo de Vigência (em meses)'),
        ),
        migrations.AlterField(
            model_name='processo',
            name='modalidade',
            field=models.CharField(choices=[('PREGAO', 'Pregão'), ('CONCORRENCIA', 'Concorrência'), ('CONCURSO', 'Concurso'), ('LEILAO', 'Leilão'), ('DIALOGO_COMPETITIVO', 'Diálogo Competitivo'), ('DISPENSA', 'Dispensa de Licitação'), ('INEXIGIBILIDADE', 'Inexigibilidade de Licitação')], max_length=30, verbose_name='Modalidade'),
        ),
        migrations.AlterField(
            model_name='processo',
            name='objeto',
            field=models.TextField(verbose_name='Objeto da Licitação (Resumido)'),
        ),
        migrations.AlterField(
            model_name='processo',
            name='valor_estimado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Valor do Contrato (Estimado)'),
        ),
    ]
