# Generated by Django 5.2.7 on 2025-10-15 17:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_processo_descricao_detalhada_objeto_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='processo',
            name='responsavel_demanda_cargo',
        ),
        migrations.RemoveField(
            model_name='processo',
            name='responsavel_demanda_matricula',
        ),
        migrations.RemoveField(
            model_name='processo',
            name='responsavel_demanda_nome',
        ),
        migrations.CreateModel(
            name='Responsavel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome Completo')),
                ('matricula', models.CharField(max_length=50, unique=True, verbose_name='Matrícula')),
                ('cargo', models.CharField(max_length=100, verbose_name='Cargo')),
                ('secretaria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.secretaria', verbose_name='Secretaria de Lotação')),
            ],
            options={
                'verbose_name': 'Responsável',
                'verbose_name_plural': 'Responsáveis',
            },
        ),
        migrations.AddField(
            model_name='processo',
            name='responsavel_demanda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.responsavel', verbose_name='Responsável pela Demanda'),
        ),
    ]
