# Generated by Django 5.2.7 on 2025-10-15 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_processo_responsavel_demanda_cargo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='processo',
            name='data_finalizacao',
        ),
        migrations.AddField(
            model_name='processo',
            name='tr_criterios_pagamento',
            field=models.TextField(blank=True, verbose_name='Critérios de Medição e Pagamento (TR)'),
        ),
        migrations.AddField(
            model_name='processo',
            name='tr_especificacoes_tecnicas',
            field=models.TextField(blank=True, verbose_name='Especificações Técnicas (TR)'),
        ),
        migrations.AddField(
            model_name='processo',
            name='tr_obrigacoes_contratada',
            field=models.TextField(blank=True, verbose_name='Obrigações da Contratada (TR)'),
        ),
        migrations.AddField(
            model_name='processo',
            name='tr_obrigacoes_contratante',
            field=models.TextField(blank=True, verbose_name='Obrigações do Contratante (TR)'),
        ),
        migrations.AddField(
            model_name='processo',
            name='tr_sancoes',
            field=models.TextField(blank=True, verbose_name='Sanções Administrativas (TR)'),
        ),
        migrations.AlterField(
            model_name='processo',
            name='descricao_detalhada_objeto',
            field=models.TextField(blank=True, verbose_name='Descrição Detalhada do Objeto/Imóvel (DFD)'),
        ),
        migrations.AlterField(
            model_name='processo',
            name='justificativa',
            field=models.TextField(blank=True, verbose_name='Justificativa da Necessidade'),
        ),
    ]
