# Generated by Django 5.2.7 on 2025-10-15 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_processo_data_finalizacao_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='processo',
            name='tr_criterios_pagamento',
        ),
        migrations.RemoveField(
            model_name='processo',
            name='tr_especificacoes_tecnicas',
        ),
        migrations.RemoveField(
            model_name='processo',
            name='tr_obrigacoes_contratada',
        ),
        migrations.RemoveField(
            model_name='processo',
            name='tr_obrigacoes_contratante',
        ),
        migrations.RemoveField(
            model_name='processo',
            name='tr_sancoes',
        ),
        migrations.AddField(
            model_name='processo',
            name='etp_forma_execucao',
            field=models.TextField(blank=True, verbose_name='Forma de Execução (ETP)'),
        ),
        migrations.AddField(
            model_name='processo',
            name='etp_justificativa_modalidade',
            field=models.TextField(blank=True, verbose_name='Justificativa da Modalidade (ETP)'),
        ),
        migrations.AddField(
            model_name='processo',
            name='etp_justificativa_objeto',
            field=models.TextField(blank=True, verbose_name='Justificativa do Objeto (ETP)'),
        ),
        migrations.AddField(
            model_name='processo',
            name='etp_justificativa_valor',
            field=models.TextField(blank=True, verbose_name='Justificativa do Valor Estimado (ETP)'),
        ),
        migrations.AddField(
            model_name='processo',
            name='etp_prazo_execucao_meses',
            field=models.IntegerField(blank=True, null=True, verbose_name='Prazo de Execução (em meses) (ETP)'),
        ),
        migrations.AddField(
            model_name='processo',
            name='etp_qualificacao_tecnica',
            field=models.TextField(blank=True, verbose_name='Qualificação Técnica Mínima (ETP)'),
        ),
        migrations.AddField(
            model_name='processo',
            name='etp_texto_legal_final',
            field=models.TextField(blank=True, verbose_name='Fundamentação Legal Final (ETP)'),
        ),
        migrations.AddField(
            model_name='processo',
            name='etp_vedacoes_participacao',
            field=models.TextField(blank=True, verbose_name='Vedações à Participação (ETP)'),
        ),
        migrations.AddField(
            model_name='processo',
            name='etp_vencimento_prorrogavel',
            field=models.TextField(blank=True, verbose_name='Vencimento e Prorrogação (ETP)'),
        ),
        migrations.AlterField(
            model_name='processo',
            name='descricao_detalhada_objeto',
            field=models.TextField(blank=True, verbose_name='Descrição Detalhada do Objeto (DFD/ETP)'),
        ),
        migrations.AlterField(
            model_name='processo',
            name='justificativa',
            field=models.TextField(blank=True, verbose_name='Justificativa da Necessidade (DFD)'),
        ),
    ]
