# Generated by Django 5.2.7 on 2025-10-16 12:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_processo_tr_criterios_pagamento_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricoProcesso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etapa', models.CharField(choices=[('DFD', 'Documento de formalização da demanda'), ('ETP', 'Estudo Técnico Preliminar (ETP)'), ('MAPA_RISCOS', 'Mapa de riscos, quando exigido'), ('TERMO_REF', 'Termo de referência ou projeto básico'), ('PESQUISA_PRECOS', 'Pesquisa de preços do mercado'), ('DOTACAO', 'Declaração de existência de dotação orçamentária'), ('PARECER_TECNICO', 'Parecer da área técnica e/ou jurídica'), ('AUTORIZACAO', 'Autorização da autoridade competente para o início'), ('EDITAL', 'Edital de licitação, incluindo anexos'), ('PUBLICACAO_AVISO', 'Publicação do aviso de licitação'), ('RECEBIMENTO_PROPOSTAS', 'Recebimento das propostas e documentos de habilitação'), ('ATA_SESSAO', 'Ata/súmula de sessão pública'), ('PLANILHA_CLASSIFICACAO', 'Planilha de classificação das propostas'), ('DOCS_HABILITACAO', 'Documentos apresentados para habilitação'), ('PARECERES_FASE_EXTERNA', 'Pareceres técnicos e jurídicos sobre propostas/habilitação'), ('RECURSOS', 'Registros de recursos administrativos'), ('JULGAMENTO_RECURSOS', 'Ata(s) de julgamento dos recursos'), ('ADJUDICACAO', 'Adjudicação do objeto ao licitante vencedor'), ('HOMOLOGACAO', 'Homologação final do resultado')], max_length=50)),
                ('data_conclusao', models.DateTimeField(auto_now_add=True)),
                ('processo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico', to='core.processo')),
            ],
            options={
                'verbose_name': 'Histórico de Etapa do Processo',
                'verbose_name_plural': 'Históricos de Etapas do Processo',
                'unique_together': {('processo', 'etapa')},
            },
        ),
    ]
