# Generated by Django 5.2.7 on 2025-10-16 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_historicoprocesso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicoprocesso',
            name='etapa',
            field=models.CharField(choices=[('DFD', 'Documento de formalização da demanda'), ('ETP', 'Estudo Técnico Preliminar (ETP)'), ('PESQUISA_PRECOS', 'Pesquisa de preços do mercado'), ('DOTACAO', 'Dotação orçamentária'), ('MAPA_RISCOS', 'Mapa de riscos, quando exigido'), ('TERMO_REF', 'Termo de referência ou projeto básico'), ('JUSTIFICATIVA', 'Justificativa'), ('PARECER_TECNICO_JURIDICO', 'Parecer da área técnica e/ou jurídica'), ('PARECER_CONTROLE_INTERNO', 'Parecer Controle Interno'), ('PEDIDO_RATIFICACAO', 'Pedido de Ratificação'), ('RATIFICACAO', 'Ratificação'), ('AUTORIZACAO', 'Autorização da autoridade competente para o início'), ('EDITAL', 'Edital de licitação, incluindo anexos'), ('PUBLICACAO_AVISO', 'Publicação do aviso de licitação'), ('RECEBIMENTO_PROPOSTAS', 'Recebimento das propostas e documentos de habilitação'), ('ATA_SESSAO', 'Ata/súmula de sessão pública'), ('PLANILHA_CLASSIFICACAO', 'Planilha de classificação das propostas'), ('DOCS_HABILITACAO', 'Documentos apresentados para habilitação'), ('PARECERES_FASE_EXTERNA', 'Pareceres técnicos e jurídicos sobre propostas/habilitação'), ('RECURSOS', 'Registros de recursos administrativos'), ('JULGAMENTO_RECURSOS', 'Ata(s) de julgamento dos recursos'), ('ADJUDICACAO', 'Adjudicação do objeto ao licitante vencedor'), ('HOMOLOGACAO', 'Homologação final do resultado')], max_length=50),
        ),
    ]
