# Generated by Django 5.2.7 on 2025-10-21 19:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_historicoprocesso_etapa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='processo',
            name='etp_forma_execucao',
        ),
        migrations.RemoveField(
            model_name='processo',
            name='etp_justificativa_modalidade',
        ),
        migrations.RemoveField(
            model_name='processo',
            name='etp_justificativa_objeto',
        ),
        migrations.RemoveField(
            model_name='processo',
            name='etp_justificativa_valor',
        ),
        migrations.RemoveField(
            model_name='processo',
            name='etp_prazo_execucao_meses',
        ),
        migrations.RemoveField(
            model_name='processo',
            name='etp_qualificacao_tecnica',
        ),
        migrations.RemoveField(
            model_name='processo',
            name='etp_texto_legal_final',
        ),
        migrations.RemoveField(
            model_name='processo',
            name='etp_vedacoes_participacao',
        ),
        migrations.RemoveField(
            model_name='processo',
            name='etp_vencimento_prorrogavel',
        ),
        migrations.AddField(
            model_name='processo',
            name='etp_alinhamento_estrategico_texto',
            field=models.TextField(blank=True, verbose_name='11. Alinhamento ao Planejamento (Texto)'),
        ),
        migrations.AddField(
            model_name='processo',
            name='etp_analise_alternativas_detalhe',
            field=models.TextField(blank=True, verbose_name='6.2. Análise de Alternativas Detalhada (ETP)'),
        ),
        migrations.AddField(
            model_name='processo',
            name='etp_analise_fornecedores_detalhe',
            field=models.TextField(blank=True, verbose_name='4.2. Análise de Fornecedores Detalhada (ETP)'),
        ),
        migrations.AddField(
            model_name='processo',
            name='etp_autoridade_competente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processos_aprovados_etp', to='core.responsavel', verbose_name='Autoridade Competente (Aprovação ETP)'),
        ),
        migrations.AddField(
            model_name='processo',
            name='etp_contratacoes_correlatas_texto',
            field=models.TextField(blank=True, default='Não há contratações correlatas e/ou interdependentes para essa aquisição.', verbose_name='11. Contratações Correlatas/Interdependentes (Texto)'),
        ),
        migrations.AddField(
            model_name='processo',
            name='etp_criterio_julgamento',
            field=models.CharField(blank=True, choices=[('MENOR_PRECO', 'Menor Preço'), ('MAIOR_DESCONTO', 'Maior Desconto'), ('MELHOR_TECNICA', 'Melhor Técnica ou Conteúdo Artístico'), ('TECNICA_PRECO', 'Técnica e Preço'), ('MAIOR_RETORNO', 'Maior Retorno Econômico')], max_length=30, verbose_name='9. Critério de Julgamento (ETP)'),
        ),
        migrations.AddField(
            model_name='processo',
            name='etp_descricao_solucao_texto',
            field=models.TextField(blank=True, default='Considerando os levantamentos realizados neste Estudo Técnico Preliminar, chegou-se à conclusão de que não há outras soluções mercadológicas a serem consideradas, a não ser a compra desses produtos por intermédio de fornecedores.\nOs quantitativos, em que pese terem sido levantados por intermédio de relatórios e ofícios para as demais secretarias requisitantes, ainda sim podem sofrer alteração no decorrer do ano, razão pela qual optou-se por realizar um pregão na modalidade registro de preços.', verbose_name='7. Descrição da Solução como um Todo (Texto)'),
        ),
        migrations.AddField(
            model_name='processo',
            name='etp_dotacao_fonte_recursos',
            field=models.CharField(blank=True, max_length=100, verbose_name='16. Dotação: Fonte de Recursos'),
        ),
        migrations.AddField(
            model_name='processo',
            name='etp_dotacao_natureza_despesa',
            field=models.CharField(blank=True, max_length=100, verbose_name='16. Dotação: Natureza da Despesa'),
        ),
        migrations.AddField(
            model_name='processo',
            name='etp_dotacao_programa_trabalho',
            field=models.CharField(blank=True, max_length=100, verbose_name='16. Dotação: Programa de Trabalho'),
        ),
        migrations.AddField(
            model_name='processo',
            name='etp_estimativa_metodologia',
            field=models.TextField(blank=True, verbose_name='6. Metodologia da Estimativa de Preços'),
        ),
        migrations.AddField(
            model_name='processo',
            name='etp_fiscal_administrativo',
            field=models.CharField(blank=True, max_length=200, verbose_name='2. Fiscal Administrativo (ETP)'),
        ),
        migrations.AddField(
            model_name='processo',
            name='etp_fiscal_tecnico',
            field=models.CharField(blank=True, max_length=200, verbose_name='2. Fiscal Técnico (ETP)'),
        ),
        migrations.AddField(
            model_name='processo',
            name='etp_gestor_contrato',
            field=models.CharField(blank=True, max_length=200, verbose_name='2. Gestor do Contrato (ETP)'),
        ),
        migrations.AddField(
            model_name='processo',
            name='etp_impactos_ambientais_texto',
            field=models.TextField(blank=True, default='Não há medidas sustentáveis ou impactos ambientais a serem considerados nessa contratação.', verbose_name='12. Possíveis Impactos Ambientais (Texto)'),
        ),
        migrations.AddField(
            model_name='processo',
            name='etp_justificativa_contratacao',
            field=models.TextField(blank=True, verbose_name='5. Justificativa da Contratação (ETP)'),
        ),
        migrations.AddField(
            model_name='processo',
            name='etp_justificativa_modalidade_criterio',
            field=models.TextField(blank=True, verbose_name='9. Justificativa da Modalidade e Critério (ETP)'),
        ),
        migrations.AddField(
            model_name='processo',
            name='etp_justificativa_parcelamento_texto',
            field=models.TextField(blank=True, default='Em se tratando de aquisição de produtos divisíveis, os quais serão comprados por intermédio de um pregão na modalidade registro de preços e que há um rol extenso de materiais diferentes que devem ser fornecidos, opta-se por executar a licitação dividida em itens, uma vez que ampliará a competitividade e não limitará os fornecedores que não possuem determinados itens para fornecimento.', verbose_name='8. Justificativas para Parcelamento (Texto)'),
        ),
        migrations.AddField(
            model_name='processo',
            name='etp_justificativa_prazo',
            field=models.TextField(blank=True, verbose_name='8. Justificativa do Prazo (ETP)'),
        ),
        migrations.AddField(
            model_name='processo',
            name='etp_lista_anexos_texto',
            field=models.TextField(blank=True, verbose_name='17. Anexos (Texto)'),
        ),
        migrations.AddField(
            model_name='processo',
            name='etp_pca_texto',
            field=models.TextField(blank=True, default='Este órgão não elaborou Plano de Contratações Anual para este ano, motivo pelo qual deixo de indicar a previsão desta contratação neste tópico.', verbose_name='2. Previsão no PCA'),
        ),
        migrations.AddField(
            model_name='processo',
            name='etp_prazo_execucao',
            field=models.IntegerField(blank=True, null=True, verbose_name='8. Prazo de Execução (em meses) (ETP)'),
        ),
        migrations.AddField(
            model_name='processo',
            name='etp_providencias_texto',
            field=models.TextField(blank=True, default='Não há providências a serem adotadas pela Administração nesta compra.', verbose_name='10. Providências a serem Adotadas (Texto)'),
        ),
        migrations.AddField(
            model_name='processo',
            name='etp_requisitos_amostra_texto',
            field=models.TextField(blank=True, default='A exigência de apresentação de amostra no processo licitatório visa garantir que os produtos ofertados atendam integralmente às especificações técnicas e aos padrões de qualidade estabelecidos no termo de referência ou no edital.\nEssa medida é fundamental para assegurar a conformidade dos itens contratados com as necessidades da Administração Pública, minimizando riscos de aquisição de materiais ou bens inadequados.\nA apresentação de amostras permite:\nVerificação da Qualidade: Avaliar se o produto ofertado possui características técnicas, materiais e acabamento compatíveis com os critérios exigidos.\nConformidade com as Especificações: Assegurar que o item atende plenamente aos requisitos estabelecidos, evitando divergências entre o que foi ofertado e o que será entregue.\nRedução de Riscos: Prevenir problemas relacionados à entrega de itens de qualidade inferior ou incompatíveis com o objeto da licitação, promovendo maior eficiência e economicidade.\nDessa forma, a exigência de amostra é um instrumento que contribui para a lisura e eficiência do processo licitatório, resguardando o interesse público e garantindo a qualidade na aquisição dos bens ou materiais necessários.', verbose_name='5. Requisitos: Amostra (Texto)'),
        ),
        migrations.AddField(
            model_name='processo',
            name='etp_requisitos_capacitacao_detalhe',
            field=models.TextField(blank=True, verbose_name='3.3. Requisitos de Capacitação Técnica Detalhados (ETP)'),
        ),
        migrations.AddField(
            model_name='processo',
            name='etp_requisitos_marcas_texto',
            field=models.TextField(blank=True, default='A fim de selecionar um fornecedor que possa atender as especificações mínimas descritas neste estudo e atendam a demanda desta Administração, foram realizadas pesquisas de mercado para verificar quais são as marcas que possuem melhor custo-benefício, com base em critérios técnicos, qualidade comprovada, durabilidade, assistência técnica disponível na região e compatibilidade com as necessidades específicas do objeto licitado.\nA indicação de marcas de referência busca assegurar a aquisição de produtos que atendam aos padrões mínimos de desempenho e eficiência, sem, contudo, restringir a competitividade, uma vez que permite a apresentação de produtos equivalentes que atendam às mesmas especificações técnicas.\nAssim, garante-se a transparência e a objetividade do processo licitatório, resguardando o interesse público e a economicidade.', verbose_name='5. Requisitos: Indicação de Marcas (Texto)'),
        ),
        migrations.AddField(
            model_name='processo',
            name='etp_requisitos_tecnicos_detalhe',
            field=models.TextField(blank=True, verbose_name='3.2. Requisitos Técnicos Detalhados (ETP)'),
        ),
        migrations.AddField(
            model_name='processo',
            name='etp_requisitos_texto_geral',
            field=models.TextField(blank=True, default='Para esta aquisição, serão exigidos os seguintes requisitos para a contratação:', verbose_name='5. Requisitos da Contratação (Texto Introdutório)'),
        ),
        migrations.AddField(
            model_name='processo',
            name='etp_responsavel_elaboracao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processos_elaborados_etp', to='core.responsavel', verbose_name='Responsável pela Elaboração (ETP)'),
        ),
        migrations.AddField(
            model_name='processo',
            name='etp_resultados_pretendidos_texto',
            field=models.TextField(blank=True, default='Como não há soluções comparativas em relação a essa compra, não há como demonstrar os resultados pretendidos em detrimento de outras hipóteses.', verbose_name='9. Demonstrativo dos Resultados Pretendidos (Texto)'),
        ),
        migrations.AddField(
            model_name='processo',
            name='etp_solucao_proposta_detalhe',
            field=models.TextField(blank=True, verbose_name='6.1. Solução Proposta Detalhada (ETP)'),
        ),
        migrations.AddField(
            model_name='processo',
            name='etp_texto_estimativa_quantidades',
            field=models.TextField(blank=True, default='Foi emitido relatório de consumo dos últimos 12 meses de todas as repartições deste órgão público, a fim de identificar os quantitativos de produtos consumidos por esta Administração.\nAlém disso, foi enviado ofício para todas as repartições que utilizam esse produto, a fim de indagar se haverá aumento de consumo em algum item específico, bem como se há algum produto extra a ser considerado para a próxima compra.\nEm que pese os levantamentos acima referidos, mensurar sua quantidade exata para uso durante o período de 12 meses não se mostra possível.\nDiante disso, opta-se por realizar pregão na modalidade registro de preços.', verbose_name='3. Estimativa das Quantidades (Texto)'),
        ),
        migrations.AddField(
            model_name='processo',
            name='etp_texto_levantamento_mercado',
            field=models.TextField(blank=True, default='Considerando que não há soluções mercadológicas a serem consideradas para a aquisição desse objeto, deixo de fazer este levantamento, especialmente porque se trata de uma compra de baixa complexidade e não há outros meios de adquirir estes itens, a não ser pela compra desses produtos com fornecedores que trabalham neste ramo.', verbose_name='4. Levantamento de Mercado (Texto)'),
        ),
        migrations.AlterField(
            model_name='processo',
            name='descricao_detalhada_objeto',
            field=models.TextField(blank=True, verbose_name='3.1. Objeto da Contratação Detalhado (DFD/ETP)'),
        ),
        migrations.AlterField(
            model_name='processo',
            name='justificativa',
            field=models.TextField(blank=True, verbose_name='1. Descrição da Necessidade (DFD/ETP)'),
        ),
        migrations.AlterField(
            model_name='processo',
            name='modalidade',
            field=models.CharField(choices=[('PREGAO', 'Pregão'), ('CONCORRENCIA', 'Concorrência'), ('CONCURSO', 'Concurso'), ('LEILAO', 'Leilão'), ('DIALOGO_COMPETITIVO', 'Diálogo Competitivo'), ('DISPENSA', 'Dispensa de Licitação'), ('INEXIGIBILIDADE', 'Inexigibilidade de Licitação')], max_length=30, verbose_name='Modalidade Sugerida'),
        ),
        migrations.AlterField(
            model_name='processo',
            name='objeto',
            field=models.TextField(verbose_name='Objeto da Contratação (Resumido)'),
        ),
        migrations.AlterField(
            model_name='processo',
            name='responsavel_demanda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processos_demandados', to='core.responsavel', verbose_name='Responsável pela Demanda (DFD)'),
        ),
        migrations.AlterField(
            model_name='processo',
            name='secretaria_responsavel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.secretaria', verbose_name='Unidade Requisitante / Setor Demandante'),
        ),
        migrations.AlterField(
            model_name='processo',
            name='valor_estimado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Valor Estimado Total'),
        ),
        migrations.AlterField(
            model_name='processo',
            name='vigencia_meses',
            field=models.IntegerField(blank=True, null=True, verbose_name='8. Vigência Contratual (em meses)'),
        ),
    ]
