# Generated by Django 5.2.7 on 2025-10-21 22:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_processo_etp_forma_execucao_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('DFD', 'Documento de Formalização da Demanda'), ('ETP', 'Estudo Técnico Preliminar'), ('TR', 'Termo de Referência')], max_length=3, verbose_name='Tipo de Documento')),
                ('arquivo', models.FileField(upload_to='documentos/%Y/%m/', verbose_name='Arquivo Gerado')),
                ('data_geracao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Geração')),
                ('gerado_por', models.CharField(blank=True, max_length=200, verbose_name='Gerado por')),
                ('processo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='core.processo', verbose_name='Processo')),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
                'ordering': ['-data_geracao'],
            },
        ),
    ]
